---
title: "Can I do this with re3data API"
author: "Dorothea Strecker, Yi Wang"
date: "22 4 2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * *
### Question 1: Can I get a list of Research data repositories regarding "COVID-19"? 

* * *
**load Packages **

```{r load-packages, results='hide', message=FALSE, warning=FALSE}
installed.packages("tidyverse")
installed.packages("htttr")
installed.packages("xml2")
installed.packages("rlist")
library(tidyverse)
library(httr)
library(xml2)
library(rlist)
```
**Extract re3data IDs of all repositories which satisfied the filter keywords="COVID-19"**

```{r }
re3data_query <- list("keywords[]" = "COVID-19") 
re3data_request <- GET("https://www.re3data.org/api/beta/repositories?", query = re3data_query) 
re3data_xml <- read_xml(re3data_request) 
re3data_IDs <- xml_text(xml_find_all(re3data_xml, xpath = "//id"))

URLs <- paste("https://www.re3data.org/api/v1/repository/",re3data_IDs, sep = "")
```
**generate function to gather detailed Information about that queried repositories**

```{r }

extract_info <- function(url) {
  list(
    re3data_ID = xml_text(xml_find_all(repository_metadata_XML, "//r3d:re3data.orgIdentifier")),
    
    repositoryName = xml_text(xml_find_all(repository_metadata_XML, "//r3d:repositoryName")),
    
    repositoryUrl = xml_text(xml_find_all(repository_metadata_XML, "//r3d:repositoryURL"))
  )
}

repository_info <- data.frame(matrix(ncol = 3, nrow = 0))

colnames(repository_info) <- c("re3data_ID", "repositoryName", "repositoryUrl")

for (url in URLs) {
  repository_metadata_request <- GET(url)
  repository_metadata_XML <-read_xml(repository_metadata_request) 
  results_list <- extract_info(repository_metadata_XML) 
  repository_info <- rbind(repository_info, results_list)
}
```

